adds election contest page
spotlightpa/poor-richard pull request #554
Opened 2024-01-22 18:34 UTC by jeffrummel

2024-01-22 19:51 UTC, carlmjohnson commented on prettier-html-ignore.rc
> +layouts/partials/tw/promo-double.html
This is a duplicate line.

2024-01-22 19:57 UTC, carlmjohnson requested changes
The error message from prettier seems to mean there's something unbalanced in the HTML. I'd like to track it down if we can. I found some spots with `/ style=aspect-ratio:128/72` but fixing that didn't balance the HTML.

2024-01-23 02:17 UTC, jeffrummel commented
> The error message from prettier seems to mean there's something unbalanced in the HTML. I'd like to track it down if we can. I found some spots with / style=aspect-ratio:128/72 but fixing that didn't balance the HTML.

I believe this is caused by missing parentheses that are stripped at build time. `style=aspect-ratio:128/72` doesn't pass validation in prettier but `style="aspect-ratio:128/72"` does. I spent some time today adding parentheses back into the links hoping that would be enough but it still wouldn't pass validation and the parentheses were stripped out on the deploy.

2024-01-23 15:33 UTC, carlmjohnson commented on content/elections-contest.md
> ++++
The blocks in here don't really work, do they? Maybe just drop them so we don't try to tweak it and forget why it's not working in 6 months.

2024-01-23 17:26 UTC, carlmjohnson approved these changes

2024-01-23 17:27 UTC, merged